version: '3.4'
secrets:
  awsKey:
    file: ./secrets/awsKey
  awsSecret:
    file: ./secrets/awsSecret
  mysqlPass:
    file: ./secrets/mysqlPass
  mysqlRootPass:
    file: ./secrets/mysqlRootPass
volumes:
  database:
services:
  app:
    image: 'codevelopinteractive/docker-backup-mysql-to-s3'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    secrets:
      - awsKey
      - awsSecret
      - mysqlPass
      - mysqlRootPass
    # volumes:
      # - ./run.sh:/run.sh
      # - ./restore.sh:/restore.sh
      # - ./backup.sh:/backup.sh
    environment:
      MYSQL_HOST: "database"
      MYSQL_USER: "root"
      MYSQL_PASSWORD_FILE: '/run/secrets/mysqlRootPass'
      S3_ACCESS_KEY_ID_FILE: '/run/secrets/awsKey'
      S3_SECRET_ACCESS_KEY_FILE: '/run/secrets/awsSecret'
      S3_BUCKET: "canvet-backups"
      S3_PREFIX: 'database-backup'
      SCHEDULE: "0 * * * * *"
    depends_on:
      - database
  database:
    image: mariadb:10.2
    restart: always
    secrets:
      - mysqlPass
      - mysqlRootPass
    environment:
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/mysqlRootPass'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD_FILE: '/run/secrets/mysqlPass'
      MYSQL_DATABASE: 'mydatabase'
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
